services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      # if you have a Postgres instance running locally, using different ports prevents conflicts
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: